spring:
  profiles:
    active : dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Root@123
    url: jdbc:mysql://114.55.127.198:82/cookie?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver

#server:
#  port: 8080

logging:
#  file: ./logs/run.log
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR

